=== api-evangelist/amazon-incident-manager/json-schema/incident-manager-update-response-plan-input-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-incident-manager/refs/heads/main/json-schema/incident-manager-update-response-plan-input-schema.json",
  "title": "UpdateResponsePlanInput",
  "description": "UpdateResponsePlanInput schema",
  "type": "object",
  "properties": {
    "actions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ActionsList"
        },
        {
          "description": "The actions that this response plan takes at the beginning of an incident."
        }
      ]
    },
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the response plan."
        }
      ]
    },
    "chatChannel": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ChatChannel"
        },
        {
          "description": "<p>The Chatbot chat channel used for collaboration during an incident.</p> <p>Use the empty structure to remove the chat channel from the response plan.</p>"
        }
      ]
    },
    "clientToken": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClientToken"
        },
        {
          "description": "A token ensuring that the operation is called only once with the specified details."
        }
      ]
    },
    "displayName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ResponsePlanDisplayName"
        },
        {
          "description": "The long format name of the response plan. The display name can't contain spaces."
        }
      ]
    },
    "engagements": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EngagementSet"
        },
        {
          "description": "The Amazon Resource Name (ARN) for the contacts and escalation plans that the response plan engages during an incident."
        }
      ]
    },
    "incidentTemplateDedupeString": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DedupeString"
        },
        {
          "description": "The string Incident Manager uses to prevent duplicate incidents from being created by the same incident in the same account."
        }
      ]
    },
    "incidentTemplateImpact": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Impact"
        },
        {
          "description": "<p>Defines the impact to the customers. Providing an impact overwrites the impact provided by a response plan.</p> <p class=\"title\"> <b>Possible impacts:</b> </p> <ul> <li> <p> <code>5</code> - Severe impact</p> </li> <li> <p> <code>4</code> - High impact</p> </li> <li> <p> <code>3</code> - Medium impact</p> </li> <li> <p> <code>2</code> - Low impact</p> </li> <li> <p> <code>1</code> - No impact</p> </li> </ul>"
        }
      ]
    },
    "incidentTemplateNotificationTargets": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NotificationTargetSet"
        },
        {
          "description": "The Amazon SNS targets that are notified when updates are made to an incident."
        }
      ]
    },
    "incidentTemplateSummary": {
      "allOf": [
        {
          "$ref": "#/components/schemas/IncidentSummary"
        },
        {
          "description": "A brief summary of the incident. This typically contains what has happened, what's currently happening, and next steps."
        }
      ]
    },
    "incidentTemplateTags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagMapUpdate"
        },
        {
          "description": "Tags to assign to the template. When the <code>StartIncident</code> API action is called, Incident Manager assigns the tags specified in the template to the incident. To call this action, you must also have permission to call the <code>TagResource</code> API action for the incident record resource."
        }
      ]
    },
    "incidentTemplateTitle": {
      "allOf": [
        {
          "$ref": "#/components/schemas/IncidentTitle"
        },
        {
          "description": "The short format name of the incident. The title can't contain spaces."
        }
      ]
    },
    "integrations": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Integrations"
        },
        {
          "description": "Information about third-party services integrated into the response plan."
        }
      ]
    }
  },
  "required": [
    "arn"
  ]
}

=== api-evangelist/amazon-incident-manager/examples/incident-manager-update-response-plan-input-example.json
{
  "actions": "example-value",
  "arn": "arn:aws:ssm-incidents::123456789012:response-plan/example",
  "chatChannel": "example-value",
  "clientToken": "example-value",
  "displayName": "example-incident",
  "engagements": "example-value",
  "incidentTemplateDedupeString": "id-abc123",
  "incidentTemplateImpact": "id-abc123",
  "incidentTemplateNotificationTargets": "id-abc123",
  "incidentTemplateSummary": "id-abc123",
  "incidentTemplateTags": "id-abc123",
  "incidentTemplateTitle": "id-abc123",
  "integrations": "example-value"
}
